// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEJ9h8VCjNDtyCeOEOvRmev4dykWSRCFY',
    appId: '1:628901640335:web:f3a0910a0d0fa87b1058fa',
    messagingSenderId: '628901640335',
    projectId: 'luis-pablo-goez-db',
    authDomain: 'luis-pablo-goez-db.firebaseapp.com',
    storageBucket: 'luis-pablo-goez-db.firebasestorage.app',
    measurementId: 'G-QW504ZTXTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASXkSdjd-Xca0U2sBVRFgnYO82KIBWKeA',
    appId: '1:628901640335:android:25f1d1a306381bfd1058fa',
    messagingSenderId: '628901640335',
    projectId: 'luis-pablo-goez-db',
    storageBucket: 'luis-pablo-goez-db.firebasestorage.app',
  );

}